name: Generate Metrics
on:
  schedule:
    - cron: 0 1 * * *

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: buehler
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Zurich
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_stars: yes
          plugin_stars_limit: 4
